
- name: Extract artifact.tar.gz
  become: true
  ansible.builtin.unarchive:
    src:  artifact.tar.gz
    dest: /home/ubuntu
    
   

- name: Executing node
  become: true
  become_user: root
  shell: |
    cd /home/ubuntu
    npm install
 #   npm uninstall -g pm2
 #   npm install -g pm2@3.2.2

- name: start pm2 server 
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup --hp /home/ubuntu

- name: start service
  become: true
  become_user: root
  shell: |
    #npm install -g pm2@3.2.2
    pm2 stop default
    cd /home/ubuntu/dist
    pm2 npm run --start
    
   


   