#- name: create opt directory for prometheus
 # file:
  #  path: /backend
 #   state: 

- name: Extract artifact.tar.gz
  become: true
  ansible.builtin.unarchive:
    src: ~/project/artifact.tar.gz
    dest: /tmp
    

- name: Install packages
  become: true
  npm:
    path: /tmp
   

- name: "start app"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
