
#- name: Extract artifact.tar.gz
 # become: true
#  ansible.builtin.unarchive:
 #   src:  artifact.tar.gz
#    dest: /home/ubuntu
    
   

#- name: Executing node
#  become: true
 # become_user: root
 # shell: |
 #   cd /home/ubuntu
 #   npm install



- name: start service1
  become: true
  become_user: root
  shell: |
    cd /home/ubuntu
    pm2  stop default
    pm2  start npm --start

- name: start pm2 server 
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup --hp /home/ubuntu

    
   


   