

- name: start server
  become: true
  become_user: root
  shell: |
    
    pm2 stop default
    pm2 start "mpm run start"
    pm2 report

- name: Creates Directory
  become: yes
  file:
    path: ~/backend
    state: directory
    mode: 0755

 #- name: Extract artifact.tar.gz
 # become: true
 # ansible.builtin.unarchive:
 #   src: ~/project/artifact.tar.gz
 #   dest: /home/ubuntu
    

 #- name: Install packages
 # become: true
 # npm:
 #   path: ~/backend
   

 #- name: Executing node
 #  become: true
 # become_user: root
 #  shell: |
 #   cd /home/ubuntu/backend
 #    npm install



   