- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory


- name: Extract artifact.tar.gz
  become: true
  ansible.builtin.unarchive:
    src:  artifact.tar.gz
    dest: /home/ubuntu/backend
    

- name: Executing node
  become: true
  become_user: root
  shell: |
    cd backend 
    #curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    #sudo apt install -y nodejs
    sudo npm install
    #sudo npm run build
   


- name: start service
  become: true
  become_user: root
  shell: |
    #pm2 stop default
    cd /home/ubuntu/backend
    sudo pm2 start npm --name backend 

- name: start pm2 server 
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup --hp /home/ubuntu

    
   


   