#- name: create opt directory for prometheus
 # file:
  #  path: /backend
 #   state: 

#- name: Creates Directory
#  become: yes
 # file:
 #   path: ~/backend
#    state: directory
 #   mode: 0755

#- name: Extract artifact.tar.gz
#  become: true
#  ansible.builtin.unarchive:
 #   src:  artifact.tar.gz
 #   dest: /home/ubuntu
    

#- name: Install packages
 # become: true
 # npm:
 #   path: ~/backend
   

- name: Executing node
  become: true
  become_user: root
  shell: |
    cd /home/ubuntu/backend
    npm install
    npm build


- name: start service
  become: true
  become_user: root
  shell: |
    cd -
    cd /home/ubuntu/backend
    ls 
    pm2 stop default
    pm2 npm start --start 
   

- name: start pm2 server
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup --hp /home/ubuntu
   