#- name: create opt directory for prometheus
 # file:
  #  path: /backend
 #   state: 

- name: Creates Directory
  become: yes
  file:
    path: ~/backend
    state: directory
    mode: 0755

- name: Extract artifact.tar.gz
  become: true
  ansible.builtin.unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/backend
    

#- name: Install packages
 # become: true
 # npm:
 #   path: ~/backend
   

name: Executing node
  become: true
  become_user: root
  shell: |
    cd ~/backend
    npm install
    npm run build
   # pm2 stop default
    pm2 start npm --name "backend" -- run start --port 3030
    pm2 status
    #cd ~/backend
    #pm2 start main.js --update-env
    #pm2 status
