- name: copy back end to EC2 instance
  copy:
    src: ~\backend\artifact.tar.gz
    dest: $HOME\artifact.tar.gz

- name: Extract artifact.tar.gz
  ansible.builtin.unarchive:
    src: artifact.tar.gz
    dest: $HOME
    remote_src: yes
