#- name: create opt directory for prometheus
 # file:
  #  path: /backend
 #   state: 

- name: Creates Directory
  become: yes
  file:
    path: ~/backend
    state: directory
    mode: 0755

- name: Extract artifact.tar.gz
  become: true
  ansible.builtin.unarchive:
    src: ~/project/artifact.tar.gz
    dest: /Home/ubuntu
    

#- name: Install packages
 # become: true
 # npm:
 #   path: ~/backend
   

- name: Executing node
  become: true
  become_user: root
  shell: |
    cd /Home/ubuntu/backend
    npm install
    cd /Home/ubuntu/backend/dist
    pm2 stop default
    pm2 start main.js
   