- name: copy back end to EC2 instance
  copy:
    src: .
    dest: $HOME

- name: Extract artifact.tar.gz
  ansible.builtin.unarchive:
    src: $HOME\artifact.tar.gz
    dest: $HOME
    remote_src: true
