global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'
    
rule_files:
 - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
   
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['ec2-54-208-133-10.compute-1.amazonaws.com:9100']    

  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: AKIA4UCQSNJ7O5QHZ6WU
        secret_key: 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
        port: 9100