version: 2.1
      
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run: cd frontend  
 
    


workflows:
  default:
    jobs:
      - build-frontend
    